# Generated by Django 4.1.3 on 2022-11-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.UniqueConstraint(fields=("item", "order"), name="One item in an order"),
        ),
    ]
